services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER_USER: ${WP_USER_USER}
      WP_USER_PASS: ${WP_USER_PASS}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: on-failure
  nginx:
    build:
      context : ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: on-failure
  #Bonus services
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - inception
    restart: on-failure

  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    depends_on:
      - wordpress
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASSWORD: ${FTP_PASSWORD}
      FTP_ROOT: /var/www/html
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - inception
    restart: on-failure

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - "8082:8082"
    networks:
      - inception
    restart: on-failure

  static-site:
    build: ./requirements/bonus/static-website
    container_name: static-website
    ports:
      - "8081:80"
    networks:
      - inception
    restart: on-failure

  portainer:
    build: ./requirements/bonus/portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9001:9000"
    networks:
      - inception
    restart: on-failure

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/redis
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/portainer

networks:
  inception:
    driver: bridge